#!/usr/bin/env bash
# 📖 Generates solver/book_data_<rules>.h in parallel shards. Usage: solver/bookgen.sh <depth> <lines|squares> [shards]
set -euo pipefail
cd "$(dirname "$0")"

depth="$1"
rules="$2"
shards="${3:-$(sysctl -n hw.ncpu)}"
case "$rules" in
  squares) identifier="Squares"; macro="SQUARES" ;;
  lines) identifier="Lines"; macro="LINES" ;;
  *) echo "rules must be lines or squares" >&2; exit 1 ;;
esac
work="../../.llm/book-$rules"
mkdir -p "$work"

clang -std=c11 -O2 -Wall -Wextra -DTT_SIZE=16782823 -DBOOK_EMPTY -o bookgen quarto.c bookgen.c

pids=()
for ((i = 0; i < shards; i++)); do
  ./bookgen "$depth" "$rules" --shard "$i/$shards" > "$work/shard-$i.txt" 2> "$work/shard-$i.log" &
  pids+=($!)
done
for pid in "${pids[@]}"; do wait "$pid"; done

cat "$work"/shard-*.txt | sort > "$work/book-$depth.txt"
count=$(wc -l < "$work/book-$depth.txt" | tr -d ' ')

{
  echo "// 📖 Generated by solver/bookgen.sh — exact values of canonical select-phase positions to depth $depth (rules: $rules)."
  echo "// Do not edit by hand. Regenerate with: solver/bookgen.sh $depth $rules"
  echo "#define BOOK_${macro}_DEPTH $depth"
  echo "#define BOOK_${macro}_ENTRIES $count"
  echo "static const BookEntry bookData${identifier}[BOOK_${macro}_ENTRIES] = {"
  awk '{ printf "    { 0x%sull, 0x%s, %d },\n", $1, $2, $3 }' "$work/book-$depth.txt"
  echo "};"
} > "book_data_$rules.h"

echo "wrote book_data_$rules.h with $count entries"
