#!/usr/bin/env bash
# 📖 Generates solver/book_data.h in parallel shards. Usage: solver/bookgen.sh <depth> [shards]
set -euo pipefail
cd "$(dirname "$0")"

depth="$1"
shards="${2:-$(sysctl -n hw.ncpu)}"
work="../.llm/book"
mkdir -p "$work"

clang -std=c11 -O2 -Wall -Wextra -DTT_SIZE=16782823 -DBOOK_EMPTY -o bookgen quarto.c bookgen.c

pids=()
for ((i = 0; i < shards; i++)); do
  ./bookgen "$depth" --shard "$i/$shards" > "$work/shard-$i.txt" 2> "$work/shard-$i.log" &
  pids+=($!)
done
for pid in "${pids[@]}"; do wait "$pid"; done

cat "$work"/shard-*.txt | sort > "$work/book-$depth.txt"
count=$(wc -l < "$work/book-$depth.txt" | tr -d ' ')

{
  echo "// 📖 Generated by solver/bookgen.sh — exact values of canonical select-phase positions to depth $depth."
  echo "// Do not edit by hand. Regenerate with: solver/bookgen.sh $depth"
  echo "#define BOOK_DEPTH $depth"
  echo "#define BOOK_ENTRIES $count"
  echo "static const BookEntry bookData[BOOK_ENTRIES] = {"
  awk '{ printf "    { 0x%sull, 0x%s, %d },\n", $1, $2, $3 }' "$work/book-$depth.txt"
  echo "};"
} > book_data.h

echo "wrote book_data.h with $count entries"
